version: '3.8'  # Updated to a compatible version

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4000:80"  # Expose nginx on port 4000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - user-service
      - chat-service
      - task-service
      - notification-service
    networks:
      - my-network
    restart: always

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      - JWT_SECRET=my_super_secret_jwt_key
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=your_database_name_here
      - POSTGRES_USER=your_username_here
      - POSTGRES_PASS=your_password_here
      - RABBITMQ_URL=amqp://rabbitmq:5672
    expose:
      - "3000"
    networks:
      - my-network
    restart: always

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      - JWT_SECRET=my_super_secret_jwt_key
      - DB_HOST=mongodb://mongo:27017/userdb
      - DB_NAME=userdb
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    expose:
      - "3001"
    networks:
      - my-network
    restart: always

  chat-service:
    build:
      context: ./chat-service
    container_name: chat-service
    environment:
      - JWT_SECRET=my_super_secret_jwt_key
      - MONGO_URI=mongodb://mongo:27017/chatdb
      - RABBITMQ_URL=amqp://rabbitmq:5672
    expose:
      - "3004"
    networks:
      - my-network
    restart: always

  task-service:
    build:
      context: ./task-service
    container_name: task-service
    environment:
      - JWT_SECRET=my_super_secret_jwt_key
      - MONGO_URI=mongodb://mongo:27017/taskdb
      - RABBITMQ_URL=amqp://rabbitmq:5672
    expose:
      - "3002"
    networks:
      - my-network
    restart: always

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - SMTP_HOST=mailbag
      - SMTP_PORT=1025
    expose:
      - "3003"
    networks:
      - my-network
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # RabbitMQ Management UI
    networks:
      - my-network
    restart: always

  mailbag:
    image: mailhog/mailhog
    container_name: mailbag
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web UI
    networks:
      - my-network
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: your_username_here
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: your_database_name_here
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  mongo_data:
  postgres_data:

networks:
  my-network:
    driver: bridge
